Repository dnd-side-project/dnd-5th-9-frontend, pull requests merged in 2021-08, with the labels that each got.

#19 [Feature/join] 회원가입 페이지 템플릿 제작
  src/App.jsx
  src/components/UI/organisms/JoinForm.jsx
  src/components/UI/organisms/LoginForm.jsx
  src/components/UI/organisms/Navbar.jsx
  src/components/UI/organisms/NavbarData.jsx
  src/components/UI/organisms/Progress.jsx
  src/components/pages/Create1.jsx
  src/components/pages/Join.jsx
Labels: 💡 FEATURE, 💻 FRONT

#21 [Feature/join] 회원가입 완료 페이지 제작
  src/App.jsx
  src/components/UI/organisms/Navbar.jsx
  src/components/UI/organisms/Progress.jsx
  src/components/pages/Join.jsx
  src/components/pages/Join2.jsx
Labels: ⛔ BUG, 💡 FEATURE, 💻 FRONT

#23 [Feature/login] 로그인 페이지 레이아웃 제작
  src/components/pages/Login.jsx
Labels: 💡 FEATURE, 💻 FRONT

#25 [Feature/find-password] 비밀번호 찾기 페이지 레이아웃
  src/App.jsx
  src/components/pages/Login.jsx
  src/components/pages/Password.jsx
  src/components/pages/Password2.jsx
  src/components/pages/Password3.jsx
Labels: 💡 FEATURE, 💻 FRONT

#27 [Style] Spoqa Han Sans Neo
  src/index.css
Labels: 🎨 STYLE, 💻 FRONT

#33 [Feature/meeting] 모임 시간 입력 페이지 레이아웃
  src/components/pages/Meeting.jsx
Labels: 💡 FEATURE, 💻 FRONT

#35 [Feature/side-navbar] 사이드바 열고 닫을 때 트랜지션 버그 수정
  src/index.css
Labels: ⛔ BUG, 🎨 STYLE, 💻 FRONT

#37 [Feature/side-navbar] 사이드바 레이아웃 변경
  public/images/Logo.png
  src/components/UI/organisms/Navbar.jsx
  src/components/UI/organisms/NavbarData.jsx
  src/components/ui/organisms/Calendar.jsx
  src/components/ui/organisms/Content.jsx
  src/components/ui/organisms/JoinForm.jsx
  src/components/ui/organisms/LoginForm.jsx
  src/components/ui/organisms/Navbar.jsx
  src/components/ui/organisms/Progress.jsx
  src/images/Logo.png
  src/index.css
  yarn.lock
Labels: 🎨 STYLE, 💡 FEATURE, 💻 FRONT

#40 [Feature/calendar] 날짜 선택 기능 캘린더 컴포넌트 추가
  package.json
  src/components/ui/organisms/Calendar.jsx
  yarn.lock
Labels: 💡 FEATURE, 💻 FRONT

#45 [Feature/meeting] 모임 시간 입력 페이지 리디자인
  src/components/pages/Meeting.jsx
  src/index.css
Labels: 🌍 ENVIRONMENT, 🎨 STYLE, 💡 FEATURE

#48 [Feature/home-page] 날짜선택과 모임정보 입력 페이지간 연결 구현
  package.json
  src/components/pages/Create.jsx
  src/components/pages/Main.jsx
  src/components/ui/organisms/BottomButton.jsx
  src/components/ui/organisms/Calendar.jsx
  yarn.lock
Labels: 💡 FEATURE, 💻 FRONT

#51 [Feature/Create] 모임정보 입력 페이지 구성하기
  package.json
  src/components/pages/Create.jsx
  src/components/pages/Meeting.jsx
  src/components/ui/organisms/CreateForm.jsx
  yarn.lock
Labels: 💡 FEATURE, 💻 FRONT

#54 [Feature/Create] Create 페이지 접근 버그 수정
  src/App.jsx
  src/components/pages/Create.jsx
  src/components/pages/Meeting.jsx
Labels: ⛔ BUG, 💡 FEATURE, 💻 FRONT

#55 [Feature/loginout] 홈페이지에서 로그인 아웃에따른 메뉴 구분 구현
  src/App.jsx
  src/components/pages/Main.jsx
  src/components/ui/organisms/Navbar.jsx
Labels: 💡 FEATURE, 💻 FRONT

#57 [Feature/url-share] meeting 페이지 url 공유
  src/components/pages/Meeting.jsx
  src/components/ui/organisms/SharePopup.jsx
  src/components/ui/organisms/ToastMessage.jsx
Labels: 💡 FEATURE, 💻 FRONT

#58 [Feature/get-url] meeting 페이지 통신 구현
  src/App.jsx
  src/components/pages/Create.jsx
  src/components/pages/Meeting.jsx
  src/components/ui/organisms/Navbar.jsx
Labels: 💡 FEATURE, 💻 FRONT

#60 [Feature/result-page] 일정 결과 페이지 구현
  src/App.jsx
  src/components/pages/Result.jsx
  src/components/pages/ResultDetail.jsx
  src/components/ui/organisms/BottomButton.jsx
  src/components/ui/organisms/Navbar.jsx
Labels: 💡 FEATURE, 💻 FRONT
